//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieReviews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateReviewed { get; set; }
        public int MovieID { get; set; }
    
        public virtual Movy Movy { get; set; }
    }
}
